# Generated by Django 5.1.7 on 2025-03-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='root', max_length=255),
            preserve_default=False,
        ),
    ]
