# Generated by Django 5.1.7 on 2025-03-29 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_media_chapters_media_plot_media_quotes_media_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Score must be at least 0'), django.core.validators.MaxValueValidator(10.0, message='Score cannot exceed 10')]),
        ),
    ]
