# Generated by Django 5.1.7 on 2025-03-29 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='usermedia',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('cinema', 'Cinema'), ('series', 'Series'), ('manga', 'Manga'), ('music', 'Music')], db_index=True, default='cinema', max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['title', 'media_type'], name='media_media_title_1e4bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['created_at', 'media_type'], name='media_media_created_4c3929_idx'),
        ),
        migrations.AddIndex(
            model_name='usermedia',
            index=models.Index(fields=['user', 'media'], name='media_userm_user_id_90a7fb_idx'),
        ),
        migrations.AddIndex(
            model_name='usermedia',
            index=models.Index(fields=['score'], name='media_userm_score_bb7d48_idx'),
        ),
    ]
