# Generated by Django 5.1.7 on 2025-04-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_alter_media_options_alter_usermedia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='state',
            field=models.IntegerField(choices=[(0, 'Check'), (1, 'Checked'), (2, 'Viewing'), (3, 'Done')], db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='usermedia',
            index=models.Index(fields=['state'], name='media_userm_state_43495c_idx'),
        ),
    ]
